// flow-typed signature: 4974d6e27021f863dd2c2e90fa67c84e
// flow-typed version: <<STUB>>/@storybook/cli_v^3.3.11/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/cli/bin/generate' {
  declare module.exports: any;
}

declare module '@storybook/cli/bin/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/ANGULAR/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/METEOR/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/METEOR/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/addons' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/style' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Welcome/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/addons' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/style' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Welcome/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/storybook' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_SCRIPTS/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/SFC_VUE/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/SFC_VUE/template/src/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/UPDATE_PACKAGE_ORGANIZATIONS/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/VUE/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/VUE/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/VUE/template/stories/MyButton' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/VUE/template/stories/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/WEBPACK_REACT/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/WEBPACK_REACT/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/detect' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/has_yarn' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/helpers' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/project_types' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/already_has_storybook/src/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/already_has_storybook/src/App.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/already_has_storybook/src/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/already_has_storybook/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/already_has_storybook/src/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/angular-cli/karma.conf' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/angular-cli/protractor.conf' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/meteor/client/main' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/meteor/server/main' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_native_scripts/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_native_scripts/App.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_native/__tests__/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_native/__tests__/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_native/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_native/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_project/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts/src/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts/src/App.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts/src/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react/rollup.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/sfc_vue/config/dev.env' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/sfc_vue/config/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/sfc_vue/config/prod.env' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/sfc_vue/src/main' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/src/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/src/App.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/src/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/stories/Button' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/stories/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/vue/public/assets/js/app' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/vue/rollup.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/vue/src/main' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/webpack_react/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/webpack_react/webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/already_has_storybook/src/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/already_has_storybook/src/App.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/already_has_storybook/src/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/already_has_storybook/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/already_has_storybook/src/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/angular-cli/karma.conf' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/angular-cli/protractor.conf' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/meteor/client/main' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/meteor/server/main' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/meteor/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native_scripts/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native_scripts/App.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/addons' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/Button/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/Button/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/CenterView/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/CenterView/style' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/Welcome/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/__tests__/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/__tests__/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/storybook/addons' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/storybook/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/storybook/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/storybook/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/storybook/stories/Button/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/storybook/stories/Button/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/storybook/stories/CenterView/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/storybook/stories/CenterView/style' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/storybook/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/storybook/stories/Welcome/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_native/storybook/storybook' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_project/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_project/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_scripts/src/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_scripts/src/App.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_scripts/src/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_scripts/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react_scripts/src/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react/rollup.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/react/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/sfc_vue/config/dev.env' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/sfc_vue/config/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/sfc_vue/config/prod.env' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/sfc_vue/src/main' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/sfc_vue/src/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/update_package_organisations/src/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/update_package_organisations/src/App.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/update_package_organisations/src/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/update_package_organisations/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/update_package_organisations/stories/Button' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/update_package_organisations/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/update_package_organisations/stories/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/vue/public/assets/js/app' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/vue/rollup.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/vue/src/main' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/vue/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/vue/stories/MyButton' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/vue/stories/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/webpack_react/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/webpack_react/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/snapshots/webpack_react/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/cli/bin/generate.js' {
  declare module.exports: $Exports<'@storybook/cli/bin/generate'>;
}
declare module '@storybook/cli/bin/index.js' {
  declare module.exports: $Exports<'@storybook/cli/bin/index'>;
}
declare module '@storybook/cli/generators/ANGULAR/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/ANGULAR/index'>;
}
declare module '@storybook/cli/generators/METEOR/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/METEOR/index'>;
}
declare module '@storybook/cli/generators/METEOR/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/METEOR/template/stories/index.stories'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/addons.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/addons'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.android'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.ios'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/style.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/style'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Welcome/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Welcome/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/addons.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/addons'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/index.android'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/index.ios'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.android'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/style.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/style'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Welcome/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Welcome/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/storybook.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/storybook'>;
}
declare module '@storybook/cli/generators/REACT_SCRIPTS/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_SCRIPTS/index'>;
}
declare module '@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/index'>;
}
declare module '@storybook/cli/generators/REACT/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT/index'>;
}
declare module '@storybook/cli/generators/REACT/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT/template/stories/index.stories'>;
}
declare module '@storybook/cli/generators/SFC_VUE/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/SFC_VUE/index'>;
}
declare module '@storybook/cli/generators/SFC_VUE/template/src/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/SFC_VUE/template/src/stories/index.stories'>;
}
declare module '@storybook/cli/generators/UPDATE_PACKAGE_ORGANIZATIONS/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/UPDATE_PACKAGE_ORGANIZATIONS/index'>;
}
declare module '@storybook/cli/generators/VUE/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/VUE/index'>;
}
declare module '@storybook/cli/generators/VUE/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/VUE/template/stories/index.stories'>;
}
declare module '@storybook/cli/generators/VUE/template/stories/MyButton.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/VUE/template/stories/MyButton'>;
}
declare module '@storybook/cli/generators/VUE/template/stories/Welcome.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/VUE/template/stories/Welcome'>;
}
declare module '@storybook/cli/generators/WEBPACK_REACT/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/WEBPACK_REACT/index'>;
}
declare module '@storybook/cli/generators/WEBPACK_REACT/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/WEBPACK_REACT/template/stories/index.stories'>;
}
declare module '@storybook/cli/lib/detect.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/detect'>;
}
declare module '@storybook/cli/lib/has_yarn.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/has_yarn'>;
}
declare module '@storybook/cli/lib/helpers.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/helpers'>;
}
declare module '@storybook/cli/lib/project_types.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/project_types'>;
}
declare module '@storybook/cli/test/fixtures/already_has_storybook/src/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/already_has_storybook/src/App'>;
}
declare module '@storybook/cli/test/fixtures/already_has_storybook/src/App.test.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/already_has_storybook/src/App.test'>;
}
declare module '@storybook/cli/test/fixtures/already_has_storybook/src/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/already_has_storybook/src/index'>;
}
declare module '@storybook/cli/test/fixtures/already_has_storybook/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/already_has_storybook/src/registerServiceWorker'>;
}
declare module '@storybook/cli/test/fixtures/already_has_storybook/src/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/already_has_storybook/src/stories/index'>;
}
declare module '@storybook/cli/test/fixtures/angular-cli/karma.conf.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/angular-cli/karma.conf'>;
}
declare module '@storybook/cli/test/fixtures/angular-cli/protractor.conf.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/angular-cli/protractor.conf'>;
}
declare module '@storybook/cli/test/fixtures/meteor/client/main.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/meteor/client/main'>;
}
declare module '@storybook/cli/test/fixtures/meteor/server/main.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/meteor/server/main'>;
}
declare module '@storybook/cli/test/fixtures/react_native_scripts/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_native_scripts/App'>;
}
declare module '@storybook/cli/test/fixtures/react_native_scripts/App.test.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_native_scripts/App.test'>;
}
declare module '@storybook/cli/test/fixtures/react_native/__tests__/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_native/__tests__/index.android'>;
}
declare module '@storybook/cli/test/fixtures/react_native/__tests__/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_native/__tests__/index.ios'>;
}
declare module '@storybook/cli/test/fixtures/react_native/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_native/index.android'>;
}
declare module '@storybook/cli/test/fixtures/react_native/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_native/index.ios'>;
}
declare module '@storybook/cli/test/fixtures/react_project/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_project/index'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts/src/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts/src/App'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts/src/App.test.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts/src/App.test'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts/src/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts/src/index'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts/src/registerServiceWorker'>;
}
declare module '@storybook/cli/test/fixtures/react/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react/index'>;
}
declare module '@storybook/cli/test/fixtures/react/rollup.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react/rollup.config'>;
}
declare module '@storybook/cli/test/fixtures/sfc_vue/config/dev.env.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/sfc_vue/config/dev.env'>;
}
declare module '@storybook/cli/test/fixtures/sfc_vue/config/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/sfc_vue/config/index'>;
}
declare module '@storybook/cli/test/fixtures/sfc_vue/config/prod.env.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/sfc_vue/config/prod.env'>;
}
declare module '@storybook/cli/test/fixtures/sfc_vue/src/main.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/sfc_vue/src/main'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/src/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/src/App'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/src/App.test.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/src/App.test'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/src/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/src/index'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/src/registerServiceWorker'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/stories/Button.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/stories/Button'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/stories/index'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/stories/Welcome.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/stories/Welcome'>;
}
declare module '@storybook/cli/test/fixtures/vue/public/assets/js/app.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/vue/public/assets/js/app'>;
}
declare module '@storybook/cli/test/fixtures/vue/rollup.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/vue/rollup.config'>;
}
declare module '@storybook/cli/test/fixtures/vue/src/main.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/vue/src/main'>;
}
declare module '@storybook/cli/test/fixtures/webpack_react/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/webpack_react/index'>;
}
declare module '@storybook/cli/test/fixtures/webpack_react/webpack.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/webpack_react/webpack.config'>;
}
declare module '@storybook/cli/test/snapshots/already_has_storybook/src/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/already_has_storybook/src/App'>;
}
declare module '@storybook/cli/test/snapshots/already_has_storybook/src/App.test.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/already_has_storybook/src/App.test'>;
}
declare module '@storybook/cli/test/snapshots/already_has_storybook/src/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/already_has_storybook/src/index'>;
}
declare module '@storybook/cli/test/snapshots/already_has_storybook/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/already_has_storybook/src/registerServiceWorker'>;
}
declare module '@storybook/cli/test/snapshots/already_has_storybook/src/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/already_has_storybook/src/stories/index'>;
}
declare module '@storybook/cli/test/snapshots/angular-cli/karma.conf.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/angular-cli/karma.conf'>;
}
declare module '@storybook/cli/test/snapshots/angular-cli/protractor.conf.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/angular-cli/protractor.conf'>;
}
declare module '@storybook/cli/test/snapshots/meteor/client/main.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/meteor/client/main'>;
}
declare module '@storybook/cli/test/snapshots/meteor/server/main.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/meteor/server/main'>;
}
declare module '@storybook/cli/test/snapshots/meteor/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/meteor/stories/index.stories'>;
}
declare module '@storybook/cli/test/snapshots/react_native_scripts/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native_scripts/App'>;
}
declare module '@storybook/cli/test/snapshots/react_native_scripts/App.test.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native_scripts/App.test'>;
}
declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/addons.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native_scripts/storybook/addons'>;
}
declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native_scripts/storybook/index'>;
}
declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/Button/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/Button/index.android'>;
}
declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/Button/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/Button/index.ios'>;
}
declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/CenterView/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/CenterView/index'>;
}
declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/CenterView/style.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/CenterView/style'>;
}
declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/index'>;
}
declare module '@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/Welcome/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native_scripts/storybook/stories/Welcome/index'>;
}
declare module '@storybook/cli/test/snapshots/react_native/__tests__/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/__tests__/index.android'>;
}
declare module '@storybook/cli/test/snapshots/react_native/__tests__/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/__tests__/index.ios'>;
}
declare module '@storybook/cli/test/snapshots/react_native/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/index.android'>;
}
declare module '@storybook/cli/test/snapshots/react_native/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/index.ios'>;
}
declare module '@storybook/cli/test/snapshots/react_native/storybook/addons.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/storybook/addons'>;
}
declare module '@storybook/cli/test/snapshots/react_native/storybook/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/storybook/index.android'>;
}
declare module '@storybook/cli/test/snapshots/react_native/storybook/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/storybook/index.ios'>;
}
declare module '@storybook/cli/test/snapshots/react_native/storybook/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/storybook/index'>;
}
declare module '@storybook/cli/test/snapshots/react_native/storybook/stories/Button/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/storybook/stories/Button/index.android'>;
}
declare module '@storybook/cli/test/snapshots/react_native/storybook/stories/Button/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/storybook/stories/Button/index.ios'>;
}
declare module '@storybook/cli/test/snapshots/react_native/storybook/stories/CenterView/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/storybook/stories/CenterView/index'>;
}
declare module '@storybook/cli/test/snapshots/react_native/storybook/stories/CenterView/style.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/storybook/stories/CenterView/style'>;
}
declare module '@storybook/cli/test/snapshots/react_native/storybook/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/storybook/stories/index'>;
}
declare module '@storybook/cli/test/snapshots/react_native/storybook/stories/Welcome/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/storybook/stories/Welcome/index'>;
}
declare module '@storybook/cli/test/snapshots/react_native/storybook/storybook.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_native/storybook/storybook'>;
}
declare module '@storybook/cli/test/snapshots/react_project/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_project/index'>;
}
declare module '@storybook/cli/test/snapshots/react_project/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_project/stories/index.stories'>;
}
declare module '@storybook/cli/test/snapshots/react_scripts/src/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_scripts/src/App'>;
}
declare module '@storybook/cli/test/snapshots/react_scripts/src/App.test.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_scripts/src/App.test'>;
}
declare module '@storybook/cli/test/snapshots/react_scripts/src/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_scripts/src/index'>;
}
declare module '@storybook/cli/test/snapshots/react_scripts/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_scripts/src/registerServiceWorker'>;
}
declare module '@storybook/cli/test/snapshots/react_scripts/src/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react_scripts/src/stories/index'>;
}
declare module '@storybook/cli/test/snapshots/react/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react/index'>;
}
declare module '@storybook/cli/test/snapshots/react/rollup.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react/rollup.config'>;
}
declare module '@storybook/cli/test/snapshots/react/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/react/stories/index.stories'>;
}
declare module '@storybook/cli/test/snapshots/sfc_vue/config/dev.env.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/sfc_vue/config/dev.env'>;
}
declare module '@storybook/cli/test/snapshots/sfc_vue/config/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/sfc_vue/config/index'>;
}
declare module '@storybook/cli/test/snapshots/sfc_vue/config/prod.env.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/sfc_vue/config/prod.env'>;
}
declare module '@storybook/cli/test/snapshots/sfc_vue/src/main.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/sfc_vue/src/main'>;
}
declare module '@storybook/cli/test/snapshots/sfc_vue/src/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/sfc_vue/src/stories/index.stories'>;
}
declare module '@storybook/cli/test/snapshots/update_package_organisations/src/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/update_package_organisations/src/App'>;
}
declare module '@storybook/cli/test/snapshots/update_package_organisations/src/App.test.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/update_package_organisations/src/App.test'>;
}
declare module '@storybook/cli/test/snapshots/update_package_organisations/src/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/update_package_organisations/src/index'>;
}
declare module '@storybook/cli/test/snapshots/update_package_organisations/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/update_package_organisations/src/registerServiceWorker'>;
}
declare module '@storybook/cli/test/snapshots/update_package_organisations/stories/Button.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/update_package_organisations/stories/Button'>;
}
declare module '@storybook/cli/test/snapshots/update_package_organisations/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/update_package_organisations/stories/index'>;
}
declare module '@storybook/cli/test/snapshots/update_package_organisations/stories/Welcome.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/update_package_organisations/stories/Welcome'>;
}
declare module '@storybook/cli/test/snapshots/vue/public/assets/js/app.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/vue/public/assets/js/app'>;
}
declare module '@storybook/cli/test/snapshots/vue/rollup.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/vue/rollup.config'>;
}
declare module '@storybook/cli/test/snapshots/vue/src/main.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/vue/src/main'>;
}
declare module '@storybook/cli/test/snapshots/vue/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/vue/stories/index.stories'>;
}
declare module '@storybook/cli/test/snapshots/vue/stories/MyButton.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/vue/stories/MyButton'>;
}
declare module '@storybook/cli/test/snapshots/vue/stories/Welcome.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/vue/stories/Welcome'>;
}
declare module '@storybook/cli/test/snapshots/webpack_react/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/webpack_react/index'>;
}
declare module '@storybook/cli/test/snapshots/webpack_react/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/webpack_react/stories/index.stories'>;
}
declare module '@storybook/cli/test/snapshots/webpack_react/webpack.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/snapshots/webpack_react/webpack.config'>;
}
